export enum GameDifficulty {
  None = 'None',
  Easy = 'Easy',
  Hard = 'Hard',
}

export enum PileType {
  Deck = 0,
  Peek = 1,
  Hearts = 2, // hearts
  Diamonds = 3, // diamonds
  Clubs = 4, // clubs
  Spades = 5, // spades
  Pile1 = 6,
  Pile2 = 7,
  Pile3 = 8,
  Pile4 = 9,
  Pile5 = 10,
  Pile6 = 11,
  Pile7 = 12,
}

export const difficultyName: Record<GameDifficulty, string> = {
  [GameDifficulty.None]: 'Pick a difficulty',
  [GameDifficulty.Easy]: 'Easy',
  [GameDifficulty.Hard]: 'Hard',
};

export type Size = {
  width: number;
  height: number;
};

export type Location = {
  left: number;
  top: number;
};

export enum CardType {
  /** HEARTS **/
  AceOfHearts,
  TwoOfHearts,
  ThreeOfHearts,
  FourOfHearts,
  FiveOfHearts,
  SixOfHearts,
  SevenOfHearts,
  EightOfHearts,
  NineOfHearts,
  TenOfHearts,
  JackOfHearts,
  QueenOfHearts,
  KingOfHearts,
  /** DIAMONDS **/
  AceOfDiamonds,
  TwoOfDiamonds,
  ThreeOfDiamonds,
  FourOfDiamonds,
  FiveOfDiamonds,
  SixOfDiamonds,
  SevenOfDiamonds,
  EightOfDiamonds,
  NineOfDiamonds,
  TenOfDiamonds,
  JackOfDiamonds,
  QueenOfDiamonds,
  KingOfDiamonds,
  /** CLUBS **/
  AceOfClubs,
  TwoOfClubs,
  ThreeOfClubs,
  FourOfClubs,
  FiveOfClubs,
  SixOfClubs,
  SevenOfClubs,
  EightOfClubs,
  NineOfClubs,
  TenOfClubs,
  JackOfClubs,
  QueenOfClubs,
  KingOfClubs,
  /** SPADES **/
  AceOfSpades,
  TwoOfSpades,
  ThreeOfSpades,
  FourOfSpades,
  FiveOfSpades,
  SixOfSpades,
  SevenOfSpades,
  EightOfSpades,
  NineOfSpades,
  TenOfSpades,
  JackOfSpades,
  QueenOfSpades,
  KingOfSpades,
}

export const CARD_TO_SUITE: Record<CardType, PileType> = {
  [CardType.AceOfHearts]: PileType.Hearts,
  [CardType.TwoOfHearts]: PileType.Hearts,
  [CardType.ThreeOfHearts]: PileType.Hearts,
  [CardType.FourOfHearts]: PileType.Hearts,
  [CardType.FiveOfHearts]: PileType.Hearts,
  [CardType.SixOfHearts]: PileType.Hearts,
  [CardType.SevenOfHearts]: PileType.Hearts,
  [CardType.EightOfHearts]: PileType.Hearts,
  [CardType.NineOfHearts]: PileType.Hearts,
  [CardType.TenOfHearts]: PileType.Hearts,
  [CardType.JackOfHearts]: PileType.Hearts,
  [CardType.QueenOfHearts]: PileType.Hearts,
  [CardType.KingOfHearts]: PileType.Hearts,
  [CardType.AceOfDiamonds]: PileType.Diamonds,
  [CardType.TwoOfDiamonds]: PileType.Diamonds,
  [CardType.ThreeOfDiamonds]: PileType.Diamonds,
  [CardType.FourOfDiamonds]: PileType.Diamonds,
  [CardType.FiveOfDiamonds]: PileType.Diamonds,
  [CardType.SixOfDiamonds]: PileType.Diamonds,
  [CardType.SevenOfDiamonds]: PileType.Diamonds,
  [CardType.EightOfDiamonds]: PileType.Diamonds,
  [CardType.NineOfDiamonds]: PileType.Diamonds,
  [CardType.TenOfDiamonds]: PileType.Diamonds,
  [CardType.JackOfDiamonds]: PileType.Diamonds,
  [CardType.QueenOfDiamonds]: PileType.Diamonds,
  [CardType.KingOfDiamonds]: PileType.Diamonds,
  [CardType.AceOfClubs]: PileType.Clubs,
  [CardType.TwoOfClubs]: PileType.Clubs,
  [CardType.ThreeOfClubs]: PileType.Clubs,
  [CardType.FourOfClubs]: PileType.Clubs,
  [CardType.FiveOfClubs]: PileType.Clubs,
  [CardType.SixOfClubs]: PileType.Clubs,
  [CardType.SevenOfClubs]: PileType.Clubs,
  [CardType.EightOfClubs]: PileType.Clubs,
  [CardType.NineOfClubs]: PileType.Clubs,
  [CardType.TenOfClubs]: PileType.Clubs,
  [CardType.JackOfClubs]: PileType.Clubs,
  [CardType.QueenOfClubs]: PileType.Clubs,
  [CardType.KingOfClubs]: PileType.Clubs,
  [CardType.AceOfSpades]: PileType.Spades,
  [CardType.TwoOfSpades]: PileType.Spades,
  [CardType.ThreeOfSpades]: PileType.Spades,
  [CardType.FourOfSpades]: PileType.Spades,
  [CardType.FiveOfSpades]: PileType.Spades,
  [CardType.SixOfSpades]: PileType.Spades,
  [CardType.SevenOfSpades]: PileType.Spades,
  [CardType.EightOfSpades]: PileType.Spades,
  [CardType.NineOfSpades]: PileType.Spades,
  [CardType.TenOfSpades]: PileType.Spades,
  [CardType.JackOfSpades]: PileType.Spades,
  [CardType.QueenOfSpades]: PileType.Spades,
  [CardType.KingOfSpades]: PileType.Spades,
};

export const CARD_IMAGES: Record<CardType | GameDifficulty, string> = {
  [GameDifficulty.None]: '/cards/back/none.png',
  [GameDifficulty.Easy]: '/cards/back/easy.png',
  [GameDifficulty.Hard]: '/cards/back/hard.png',
  [CardType.AceOfHearts]: '/cards/heart/1_heart.png',
  [CardType.TwoOfHearts]: '/cards/heart/2_heart.png',
  [CardType.ThreeOfHearts]: '/cards/heart/3_heart.png',
  [CardType.FourOfHearts]: '/cards/heart/4_heart.png',
  [CardType.FiveOfHearts]: '/cards/heart/5_heart.png',
  [CardType.SixOfHearts]: '/cards/heart/6_heart.png',
  [CardType.SevenOfHearts]: '/cards/heart/7_heart.png',
  [CardType.EightOfHearts]: '/cards/heart/8_heart.png',
  [CardType.NineOfHearts]: '/cards/heart/9_heart.png',
  [CardType.TenOfHearts]: '/cards/heart/10_heart.png',
  [CardType.JackOfHearts]: '/cards/heart/11_heart.png',
  [CardType.QueenOfHearts]: '/cards/heart/12_heart.png',
  [CardType.KingOfHearts]: '/cards/heart/13_heart.png',
  [CardType.AceOfDiamonds]: '/cards/diamond/1_diamond.png',
  [CardType.TwoOfDiamonds]: '/cards/diamond/2_diamond.png',
  [CardType.ThreeOfDiamonds]: '/cards/diamond/3_diamond.png',
  [CardType.FourOfDiamonds]: '/cards/diamond/4_diamond.png',
  [CardType.FiveOfDiamonds]: '/cards/diamond/5_diamond.png',
  [CardType.SixOfDiamonds]: '/cards/diamond/6_diamond.png',
  [CardType.SevenOfDiamonds]: '/cards/diamond/7_diamond.png',
  [CardType.EightOfDiamonds]: '/cards/diamond/8_diamond.png',
  [CardType.NineOfDiamonds]: '/cards/diamond/9_diamond.png',
  [CardType.TenOfDiamonds]: '/cards/diamond/10_diamond.png',
  [CardType.JackOfDiamonds]: '/cards/diamond/11_diamond.png',
  [CardType.QueenOfDiamonds]: '/cards/diamond/12_diamond.png',
  [CardType.KingOfDiamonds]: '/cards/diamond/13_diamond.png',
  [CardType.AceOfClubs]: '/cards/club/1_club.png',
  [CardType.TwoOfClubs]: '/cards/club/2_club.png',
  [CardType.ThreeOfClubs]: '/cards/club/3_club.png',
  [CardType.FourOfClubs]: '/cards/club/4_club.png',
  [CardType.FiveOfClubs]: '/cards/club/5_club.png',
  [CardType.SixOfClubs]: '/cards/club/6_club.png',
  [CardType.SevenOfClubs]: '/cards/club/7_club.png',
  [CardType.EightOfClubs]: '/cards/club/8_club.png',
  [CardType.NineOfClubs]: '/cards/club/9_club.png',
  [CardType.TenOfClubs]: '/cards/club/10_club.png',
  [CardType.JackOfClubs]: '/cards/club/11_club.png',
  [CardType.QueenOfClubs]: '/cards/club/12_club.png',
  [CardType.KingOfClubs]: '/cards/club/13_club.png',
  [CardType.AceOfSpades]: '/cards/spade/1_spade.png',
  [CardType.TwoOfSpades]: '/cards/spade/2_spade.png',
  [CardType.ThreeOfSpades]: '/cards/spade/3_spade.png',
  [CardType.FourOfSpades]: '/cards/spade/4_spade.png',
  [CardType.FiveOfSpades]: '/cards/spade/5_spade.png',
  [CardType.SixOfSpades]: '/cards/spade/6_spade.png',
  [CardType.SevenOfSpades]: '/cards/spade/7_spade.png',
  [CardType.EightOfSpades]: '/cards/spade/8_spade.png',
  [CardType.NineOfSpades]: '/cards/spade/9_spade.png',
  [CardType.TenOfSpades]: '/cards/spade/10_spade.png',
  [CardType.JackOfSpades]: '/cards/spade/11_spade.png',
  [CardType.QueenOfSpades]: '/cards/spade/12_spade.png',
  [CardType.KingOfSpades]: '/cards/spade/13_spade.png',
};

// used to provide type safety for the cards list below
export const ACTIVE_CARDS: Record<CardType, boolean> = {
  [CardType.AceOfHearts]: true,
  [CardType.TwoOfHearts]: true,
  [CardType.ThreeOfHearts]: true,
  [CardType.FourOfHearts]: true,
  [CardType.FiveOfHearts]: true,
  [CardType.SixOfHearts]: true,
  [CardType.SevenOfHearts]: true,
  [CardType.EightOfHearts]: true,
  [CardType.NineOfHearts]: true,
  [CardType.TenOfHearts]: true,
  [CardType.JackOfHearts]: true,
  [CardType.QueenOfHearts]: true,
  [CardType.KingOfHearts]: true,
  [CardType.AceOfDiamonds]: true,
  [CardType.TwoOfDiamonds]: true,
  [CardType.ThreeOfDiamonds]: true,
  [CardType.FourOfDiamonds]: true,
  [CardType.FiveOfDiamonds]: true,
  [CardType.SixOfDiamonds]: true,
  [CardType.SevenOfDiamonds]: true,
  [CardType.EightOfDiamonds]: true,
  [CardType.NineOfDiamonds]: true,
  [CardType.TenOfDiamonds]: true,
  [CardType.JackOfDiamonds]: true,
  [CardType.QueenOfDiamonds]: true,
  [CardType.KingOfDiamonds]: true,
  [CardType.AceOfClubs]: true,
  [CardType.TwoOfClubs]: true,
  [CardType.ThreeOfClubs]: true,
  [CardType.FourOfClubs]: true,
  [CardType.FiveOfClubs]: true,
  [CardType.SixOfClubs]: true,
  [CardType.SevenOfClubs]: true,
  [CardType.EightOfClubs]: true,
  [CardType.NineOfClubs]: true,
  [CardType.TenOfClubs]: true,
  [CardType.JackOfClubs]: true,
  [CardType.QueenOfClubs]: true,
  [CardType.KingOfClubs]: true,
  [CardType.AceOfSpades]: true,
  [CardType.TwoOfSpades]: true,
  [CardType.ThreeOfSpades]: true,
  [CardType.FourOfSpades]: true,
  [CardType.FiveOfSpades]: true,
  [CardType.SixOfSpades]: true,
  [CardType.SevenOfSpades]: true,
  [CardType.EightOfSpades]: true,
  [CardType.NineOfSpades]: true,
  [CardType.TenOfSpades]: true,
  [CardType.JackOfSpades]: true,
  [CardType.QueenOfSpades]: true,
  [CardType.KingOfSpades]: true,
};

export const CARDS = Object.keys(ACTIVE_CARDS).map((key) => Number(key));

export const areOppositeColors = (suite1: number, suite2: number) => {
  // hearts and diamonds are red and are piles 2 and 3
  // clubs and spades are black and are piles 4 and 5
  return (
    ((suite1 === 2 || suite1 === 3) && (suite2 === 4 || suite2 === 5)) ||
    ((suite1 === 4 || suite1 === 5) && (suite2 === 2 || suite2 === 3))
  );
};

export const CARDS_PER_SUITE = 13;
export const MAX_CARD_VALUE = CARDS_PER_SUITE - 1; // 0-based index
