import { GameDifficulty, PileType } from './enums';

export enum CardType {
  /** HEARTS **/
  AceOfHearts,
  TwoOfHearts,
  ThreeOfHearts,
  FourOfHearts,
  FiveOfHearts,
  SixOfHearts,
  SevenOfHearts,
  EightOfHearts,
  NineOfHearts,
  TenOfHearts,
  JackOfHearts,
  QueenOfHearts,
  KingOfHearts,
  /** DIAMONDS **/
  AceOfDiamonds,
  TwoOfDiamonds,
  ThreeOfDiamonds,
  FourOfDiamonds,
  FiveOfDiamonds,
  SixOfDiamonds,
  SevenOfDiamonds,
  EightOfDiamonds,
  NineOfDiamonds,
  TenOfDiamonds,
  JackOfDiamonds,
  QueenOfDiamonds,
  KingOfDiamonds,
  /** CLUBS **/
  AceOfClubs,
  TwoOfClubs,
  ThreeOfClubs,
  FourOfClubs,
  FiveOfClubs,
  SixOfClubs,
  SevenOfClubs,
  EightOfClubs,
  NineOfClubs,
  TenOfClubs,
  JackOfClubs,
  QueenOfClubs,
  KingOfClubs,
  /** SPADES **/
  AceOfSpades,
  TwoOfSpades,
  ThreeOfSpades,
  FourOfSpades,
  FiveOfSpades,
  SixOfSpades,
  SevenOfSpades,
  EightOfSpades,
  NineOfSpades,
  TenOfSpades,
  JackOfSpades,
  QueenOfSpades,
  KingOfSpades,
}

export const CARD_TO_SUITE: Record<CardType, PileType> = {
  [CardType.AceOfHearts]: PileType.Hearts,
  [CardType.TwoOfHearts]: PileType.Hearts,
  [CardType.ThreeOfHearts]: PileType.Hearts,
  [CardType.FourOfHearts]: PileType.Hearts,
  [CardType.FiveOfHearts]: PileType.Hearts,
  [CardType.SixOfHearts]: PileType.Hearts,
  [CardType.SevenOfHearts]: PileType.Hearts,
  [CardType.EightOfHearts]: PileType.Hearts,
  [CardType.NineOfHearts]: PileType.Hearts,
  [CardType.TenOfHearts]: PileType.Hearts,
  [CardType.JackOfHearts]: PileType.Hearts,
  [CardType.QueenOfHearts]: PileType.Hearts,
  [CardType.KingOfHearts]: PileType.Hearts,
  [CardType.AceOfDiamonds]: PileType.Diamonds,
  [CardType.TwoOfDiamonds]: PileType.Diamonds,
  [CardType.ThreeOfDiamonds]: PileType.Diamonds,
  [CardType.FourOfDiamonds]: PileType.Diamonds,
  [CardType.FiveOfDiamonds]: PileType.Diamonds,
  [CardType.SixOfDiamonds]: PileType.Diamonds,
  [CardType.SevenOfDiamonds]: PileType.Diamonds,
  [CardType.EightOfDiamonds]: PileType.Diamonds,
  [CardType.NineOfDiamonds]: PileType.Diamonds,
  [CardType.TenOfDiamonds]: PileType.Diamonds,
  [CardType.JackOfDiamonds]: PileType.Diamonds,
  [CardType.QueenOfDiamonds]: PileType.Diamonds,
  [CardType.KingOfDiamonds]: PileType.Diamonds,
  [CardType.AceOfClubs]: PileType.Clubs,
  [CardType.TwoOfClubs]: PileType.Clubs,
  [CardType.ThreeOfClubs]: PileType.Clubs,
  [CardType.FourOfClubs]: PileType.Clubs,
  [CardType.FiveOfClubs]: PileType.Clubs,
  [CardType.SixOfClubs]: PileType.Clubs,
  [CardType.SevenOfClubs]: PileType.Clubs,
  [CardType.EightOfClubs]: PileType.Clubs,
  [CardType.NineOfClubs]: PileType.Clubs,
  [CardType.TenOfClubs]: PileType.Clubs,
  [CardType.JackOfClubs]: PileType.Clubs,
  [CardType.QueenOfClubs]: PileType.Clubs,
  [CardType.KingOfClubs]: PileType.Clubs,
  [CardType.AceOfSpades]: PileType.Spades,
  [CardType.TwoOfSpades]: PileType.Spades,
  [CardType.ThreeOfSpades]: PileType.Spades,
  [CardType.FourOfSpades]: PileType.Spades,
  [CardType.FiveOfSpades]: PileType.Spades,
  [CardType.SixOfSpades]: PileType.Spades,
  [CardType.SevenOfSpades]: PileType.Spades,
  [CardType.EightOfSpades]: PileType.Spades,
  [CardType.NineOfSpades]: PileType.Spades,
  [CardType.TenOfSpades]: PileType.Spades,
  [CardType.JackOfSpades]: PileType.Spades,
  [CardType.QueenOfSpades]: PileType.Spades,
  [CardType.KingOfSpades]: PileType.Spades,
};

export const CARD_IMAGES: Record<CardType | GameDifficulty, string> = {
  [GameDifficulty.None]: '/cards/back4.png',
  [GameDifficulty.Easy]: '/cards/back3.png',
  [GameDifficulty.Hard]: '/cards/back2.png',
  [CardType.AceOfHearts]: '/cards/heart-1.png',
  [CardType.TwoOfHearts]: '/cards/heart-2.png',
  [CardType.ThreeOfHearts]: '/cards/heart-3.png',
  [CardType.FourOfHearts]: '/cards/heart-4.png',
  [CardType.FiveOfHearts]: '/cards/heart-5.png',
  [CardType.SixOfHearts]: '/cards/heart-6.png',
  [CardType.SevenOfHearts]: '/cards/heart-7.png',
  [CardType.EightOfHearts]: '/cards/heart-8.png',
  [CardType.NineOfHearts]: '/cards/heart-9.png',
  [CardType.TenOfHearts]: '/cards/heart-10.png',
  [CardType.JackOfHearts]: '/cards/heart-11.png',
  [CardType.QueenOfHearts]: '/cards/heart-12.png',
  [CardType.KingOfHearts]: '/cards/heart-13.png',
  [CardType.AceOfDiamonds]: '/cards/diamond-1.png',
  [CardType.TwoOfDiamonds]: '/cards/diamond-2.png',
  [CardType.ThreeOfDiamonds]: '/cards/diamond-3.png',
  [CardType.FourOfDiamonds]: '/cards/diamond-4.png',
  [CardType.FiveOfDiamonds]: '/cards/diamond-5.png',
  [CardType.SixOfDiamonds]: '/cards/diamond-6.png',
  [CardType.SevenOfDiamonds]: '/cards/diamond-7.png',
  [CardType.EightOfDiamonds]: '/cards/diamond-8.png',
  [CardType.NineOfDiamonds]: '/cards/diamond-9.png',
  [CardType.TenOfDiamonds]: '/cards/diamond-10.png',
  [CardType.JackOfDiamonds]: '/cards/diamond-11.png',
  [CardType.QueenOfDiamonds]: '/cards/diamond-12.png',
  [CardType.KingOfDiamonds]: '/cards/diamond-13.png',
  [CardType.AceOfClubs]: '/cards/club-1.png',
  [CardType.TwoOfClubs]: '/cards/club-2.png',
  [CardType.ThreeOfClubs]: '/cards/club-3.png',
  [CardType.FourOfClubs]: '/cards/club-4.png',
  [CardType.FiveOfClubs]: '/cards/club-5.png',
  [CardType.SixOfClubs]: '/cards/club-6.png',
  [CardType.SevenOfClubs]: '/cards/club-7.png',
  [CardType.EightOfClubs]: '/cards/club-8.png',
  [CardType.NineOfClubs]: '/cards/club-9.png',
  [CardType.TenOfClubs]: '/cards/club-10.png',
  [CardType.JackOfClubs]: '/cards/club-11.png',
  [CardType.QueenOfClubs]: '/cards/club-12.png',
  [CardType.KingOfClubs]: '/cards/club-13.png',
  [CardType.AceOfSpades]: '/cards/spade-1.png',
  [CardType.TwoOfSpades]: '/cards/spade-2.png',
  [CardType.ThreeOfSpades]: '/cards/spade-3.png',
  [CardType.FourOfSpades]: '/cards/spade-4.png',
  [CardType.FiveOfSpades]: '/cards/spade-5.png',
  [CardType.SixOfSpades]: '/cards/spade-6.png',
  [CardType.SevenOfSpades]: '/cards/spade-7.png',
  [CardType.EightOfSpades]: '/cards/spade-8.png',
  [CardType.NineOfSpades]: '/cards/spade-9.png',
  [CardType.TenOfSpades]: '/cards/spade-10.png',
  [CardType.JackOfSpades]: '/cards/spade-11.png',
  [CardType.QueenOfSpades]: '/cards/spade-12.png',
  [CardType.KingOfSpades]: '/cards/spade-13.png',
};

// used to provide type safety for the cards list below
export const ACTIVE_CARDS: Record<CardType, boolean> = {
  [CardType.AceOfHearts]: true,
  [CardType.TwoOfHearts]: true,
  [CardType.ThreeOfHearts]: true,
  [CardType.FourOfHearts]: true,
  [CardType.FiveOfHearts]: true,
  [CardType.SixOfHearts]: true,
  [CardType.SevenOfHearts]: true,
  [CardType.EightOfHearts]: true,
  [CardType.NineOfHearts]: true,
  [CardType.TenOfHearts]: true,
  [CardType.JackOfHearts]: true,
  [CardType.QueenOfHearts]: true,
  [CardType.KingOfHearts]: true,
  [CardType.AceOfDiamonds]: true,
  [CardType.TwoOfDiamonds]: true,
  [CardType.ThreeOfDiamonds]: true,
  [CardType.FourOfDiamonds]: true,
  [CardType.FiveOfDiamonds]: true,
  [CardType.SixOfDiamonds]: true,
  [CardType.SevenOfDiamonds]: true,
  [CardType.EightOfDiamonds]: true,
  [CardType.NineOfDiamonds]: true,
  [CardType.TenOfDiamonds]: true,
  [CardType.JackOfDiamonds]: true,
  [CardType.QueenOfDiamonds]: true,
  [CardType.KingOfDiamonds]: true,
  [CardType.AceOfClubs]: true,
  [CardType.TwoOfClubs]: true,
  [CardType.ThreeOfClubs]: true,
  [CardType.FourOfClubs]: true,
  [CardType.FiveOfClubs]: true,
  [CardType.SixOfClubs]: true,
  [CardType.SevenOfClubs]: true,
  [CardType.EightOfClubs]: true,
  [CardType.NineOfClubs]: true,
  [CardType.TenOfClubs]: true,
  [CardType.JackOfClubs]: true,
  [CardType.QueenOfClubs]: true,
  [CardType.KingOfClubs]: true,
  [CardType.AceOfSpades]: true,
  [CardType.TwoOfSpades]: true,
  [CardType.ThreeOfSpades]: true,
  [CardType.FourOfSpades]: true,
  [CardType.FiveOfSpades]: true,
  [CardType.SixOfSpades]: true,
  [CardType.SevenOfSpades]: true,
  [CardType.EightOfSpades]: true,
  [CardType.NineOfSpades]: true,
  [CardType.TenOfSpades]: true,
  [CardType.JackOfSpades]: true,
  [CardType.QueenOfSpades]: true,
  [CardType.KingOfSpades]: true,
};

export const CARDS = Object.keys(ACTIVE_CARDS).map((key) => Number(key));
