import { verifyPuzzle } from './utility';

export type PuzzleRule = 'no-3-letter-words' | 'no-4-letter-words';

export const printPuzzleRule = (rules: PuzzleRule[]) => {
  if (rules.includes('no-4-letter-words')) {
    return 'No 3 or 4 Letter Words';
  } else if (rules.includes('no-3-letter-words')) {
    return 'No 3 Letter Words';
  }
};

export type Puzzle = {
  letters: string[];
  words: string[];
  bonuses: string[];
  rules: PuzzleRule[];
};

export const puzzles: Puzzle[] = [
  {
    letters: 'work'.split(''),
    words: ['work', 'row'],
    bonuses: ['wok'],
    rules: [],
  },
  {
    letters: 'sheet'.split(''),
    words: ['sheet', 'these', 'see', 'she', 'set', 'the'],
    bonuses: ['hest', 'seth', 'thee', 'tee', 'tees'],
    rules: [],
  },
  {
    letters: 'tent'.split(''),
    words: ['tent', 'net', 'ten'],
    bonuses: ['tet'],
    rules: [],
  },
  {
    letters: 'type'.split(''),
    words: ['type', 'yet', 'pet'],
    bonuses: ['tye', 'pye', 'yep'],
    rules: [],
  },
  {
    letters: 'page'.split(''),
    words: ['page', 'gape', 'age', 'ape', 'gap', 'peg'],
    bonuses: ['peag', 'pea', 'gae'],
    rules: [],
  },
  {
    letters: 'spank'.split(''),
    words: ['spank', 'naps', 'pans', 'pan', 'sank', 'snap', 'span'],
    bonuses: ['knaps', 'san'],
    rules: [],
  },
  {
    letters: 'boat'.split(''),
    words: ['boat', 'bat', 'boa', 'bot', 'tab', 'oat'],
    bonuses: ['tao', 'bota', 'bato'],
    rules: [],
  },
  {
    letters: 'break'.split(''),
    words: ['baker', 'break', 'brake', 'bake', 'bare', 'bark', 'bear', 'rake'],
    bonuses: ['berk', 'kerb', 'bae', 'erk', 'rea', 'reb'],
    rules: [],
  },
  {
    letters: 'supply'.split(''),
    words: [
      'supply',
      'pulpy',
      'plus',
      'pulp',
      'pulps',
      'pups',
      'ply',
      'sly',
      'spy',
    ],
    bonuses: ['yups', 'pus', 'ups', 'yup', 'yus', 'sup'],
    rules: [],
  },
  {
    letters: 'cream'.split(''),
    words: [
      'cream',
      'acre',
      'came',
      'care',
      'cram',
      'mace',
      'mare',
      'race',
      'ram',
      'ace',
      'arm',
      'car',
      'ear',
      'are',
    ],
    bonuses: ['acme', 'rec', 'rem', 'mac', 'era', 'cam', 'arc', 'mar'],
    rules: [],
  },
  {
    letters: 'spring'.split(''),
    words: [
      'spring',
      'grips',
      'rings',
      'grip',
      'grin',
      'pigs',
      'pins',
      'rigs',
      'ring',
      'sign',
      'sing',
      'spin',
      'snip',
    ],
    bonuses: [
      'pings',
      'sprig',
      'gins',
      'nips',
      'ping',
      'snig',
      'rins',
      'rips',
      'gips',
    ],
    rules: ['no-3-letter-words'],
  },
  {
    letters: 'bottle'.split(''),
    words: [
      'bottle',
      'belt',
      'bolt',
      'lobe',
      'lot',
      'bot',
      'lob',
      'toe',
      'let',
      'bet',
    ],
    bonuses: [
      'tote',
      'bel',
      'bol',
      'ole',
      'botel',
      'botte',
      'lotte',
      'obe',
      'tet',
    ],
    rules: [],
  },
  {
    letters: 'sight'.split(''),
    words: [
      'sight',
      'gist',
      'sigh',
      'hits',
      'this',
      'his',
      'hit',
      'its',
      'sit',
    ],
    bonuses: ['hist', 'shit', 'sith'],
    rules: [],
  },
  {
    letters: 'camped'.split(''),
    words: [
      'camped',
      'caped',
      'paced',
      'maced',
      'came',
      'camp',
      'cape',
      'damp',
      'mace',
      'made',
      'pace',
    ],
    bonuses: ['acme', 'aced', 'dace', 'mead', 'dame'],
    rules: ['no-3-letter-words'],
  },
  {
    letters: 'bread'.split(''),
    words: [
      'beard',
      'bread',
      'bard',
      'bare',
      'bead',
      'bear',
      'bred',
      'dare',
      'dear',
      'drab',
      'read',
    ],
    bonuses: ['barde', 'bared', 'bade', 'brad'],
    rules: ['no-3-letter-words'],
  },
  {
    letters: 'blown'.split(''),
    words: [
      'blown',
      'blow',
      'bowl',
      'bow',
      'lob',
      'low',
      'now',
      'owl',
      'own',
      'won',
    ],
    bonuses: ['lown', 'bon', 'nob'],
    rules: [],
  },
  {
    letters: 'unite'.split(''),
    words: [
      'unite',
      'untie',
      'tune',
      'unit',
      'net',
      'nut',
      'ten',
      'tie',
      'tin',
    ],
    bonuses: ['nit', 'ute', 'nuit', 'tine'],
    rules: [],
  },
  {
    letters: 'cried'.split(''),
    words: [
      'cried',
      'cider',
      'dicer',
      'riced',
      'dice',
      'dire',
      'iced',
      'rice',
      'ride',
      'die',
      'red',
      'rid',
    ],
    bonuses: ['ire', 'rec', 'rei'],
    rules: [],
  },
  {
    letters: 'toffee'.split(''),
    words: ['toffee', 'feet', 'fee', 'off', 'tee', 'toe'],
    bonuses: ['fet', 'foe', 'oft', 'toff'],
    rules: [],
  },
  {
    letters: 'apple'.split(''),
    words: ['apple', 'leap', 'pale', 'plea', 'ape', 'app', 'lap', 'pea'],
    bonuses: ['ale', 'alp', 'pal', 'pep', 'peal', 'pap'],
    rules: [],
  },
  {
    letters: 'plate'.split(''),
    words: [
      'plate',
      'leapt',
      'petal',
      'late',
      'leap',
      'pale',
      'pelt',
      'plea',
      'tale',
      'tape',
      'teal',
    ],
    bonuses: ['pleat', 'leat', 'lept', 'pate', 'peal', 'peat', 'tael', 'tela'],
    rules: ['no-3-letter-words'],
  },
  {
    letters: 'water'.split(''),
    words: [
      'water',
      'rate',
      'tear',
      'ware',
      'wart',
      'wear',
      'are',
      'awe',
      'ear',
      'eat',
      'raw',
      'tar',
      'rat',
      'tea',
      'war',
      'wet',
    ],
    bonuses: ['era', 'taw', 'tew', 'wat', 'arte', 'tare'],
    rules: [],
  },
  {
    letters: 'clams'.split(''),
    words: ['clams', 'clam', 'cams', 'calm', 'scam', 'slam', 'cam'],
    bonuses: ['calms', 'alms', 'cals', 'salm', 'macs', 'mac', 'lam'],
    rules: [],
  },
];

for (const puzzle of puzzles) {
  verifyPuzzle(puzzle);
}
