import { o, x } from './util';

export const tutorial1 = [
  [x, x, x],
  [o, o, o],
  [x, x, x],
];
export const tutorial2 = [
  [o, o, o],
  [o, x, o],
  [o, o, o],
];
export const tutorial3 = [
  [o, x, x, o],
  [x, x, x, x],
  [o, x, x, o],
  [o, o, o, o],
];

export const chick = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, x, x],
  [x, x, x, o, o, x, x, x],
  [x, x, x, o, o, x, x, x],
];

export const chicken = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, x],
  [x, x, x, x, o, o, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, x, x, x],
  [x, x, x, o, x, x, x, x],
];

export const cow = [
  [x, x, x, o, o, x, o, x],
  [x, o, o, o, o, o, o, o],
  [x, o, o, o, o, o, o, o],
  [x, o, o, o, o, o, o, o],
  [x, o, o, o, o, o, o, o],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, x, o, o, x],
  [x, o, o, x, x, o, o, x],
];

export const cat = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x],
  [x, o, x, x, o, x, o, x],
  [x, o, x, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, x, x],
  [x, o, x, x, x, o, x, x],
];

export const chef = [
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const dog = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, x],
  [x, x, x, x, o, o, x, x],
  [x, x, x, x, o, o, o, x],
  [x, o, x, o, o, o, x, x],
  [x, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, x, x],
];

export const duck = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x],
  [x, x, x, x, x, o, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, x, o, x, x, x],
];

export const farmer = [
  [x, x, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, x, x, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const fox = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, o, x, x, o, x, x, x],
  [x, o, x, x, o, o, x, x],
  [x, x, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, x, x, o, x, x],
  [x, o, x, x, x, x, o, x],
];

export const goat = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, o, x, x, o, x, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, x, x, o, x, o, x],
  [x, o, x, x, o, x, x, x],
];

export const goose = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x],
  [x, x, x, x, x, o, x, x],
  [x, x, x, x, x, o, x, x],
  [x, x, x, o, o, o, x, x],
  [x, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, x, o, x, x, x],
];

export const house = [
  [x, x, x, o, o, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
];

export const pig = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, x, x, x],
  [x, o, x, x, o, x, x, x],
];

export const rock = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, o, o, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
];

export const sheep = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, x, x, x],
  [x, x, o, x, x, o, x, x],
];

export const shrub = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, o, o, x, x, x],
];

export const axe = [
  [x, x, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, o, o, o, x, x, x],
  [x, o, o, x, o, o, x, x],
  [x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x],
];

export const bacon = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const beanstalk = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x],
  [x, x, x, x, o, x, x, x],
  [x, o, o, x, o, x, x, x],
  [x, x, x, o, o, x, x, x],
  [x, x, x, o, o, o, o, x],
  [x, x, x, o, o, x, x, x],
  [x, x, x, o, o, x, x, x],
];

export const beat = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x],
  [x, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x],
];

export const carrot = [
  [x, x, x, x, x, x, x, x],
  [x, o, x, x, x, x, x, x],
  [x, x, o, o, x, x, x, x],
  [x, x, o, o, o, x, x, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x],
];

export const hatchet = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, o, x, x, x, x],
  [x, o, o, o, o, x, x, x],
  [x, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, x, x],
  [x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x],
];

export const corn = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x],
  [x, o, x, o, o, o, o, x],
  [x, x, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, x, x, x],
  [x, o, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const meat = [
  [x, x, x, x, x, x, x, x],
  [x, o, o, o, o, x, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const pail = [
  [x, x, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, o, o, o, x, o, x],
  [x, x, o, o, o, x, o, x],
  [x, x, o, o, o, x, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const peas = [
  [x, x, x, x, x, x, x, x],
  [x, o, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, x],
  [x, x, x, x, x, x, x, x],
];

export const pepper = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, x, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, x],
  [x, x, x, x, x, x, x, x],
];

export const pickaxe = [
  [x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, o, o, o, x, x, x],
  [x, o, x, x, o, o, x, x],
  [x, o, x, x, x, o, o, x],
  [x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x],
];

export const plum = [
  [x, x, x, x, x, x, x, x],
  [x, o, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x],
  [x, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, x],
  [x, x, x, x, x, x, x, x],
];

export const potato = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, x, x],
  [x, x, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x],
];

export const reeds = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x],
  [x, x, x, o, x, x, x, x],
  [x, x, x, o, x, o, o, x],
  [x, x, o, o, o, x, x, x],
  [x, o, x, o, o, x, x, x],
  [x, x, x, o, o, x, x, x],
  [x, x, x, o, o, x, x, x],
];

export const tomato = [
  [x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, o, x],
  [x, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x],
];

export const sickle = [
  [x, x, x, x, x, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, o, o, x, x, x, x],
  [x, o, x, o, o, x, o, x],
  [x, o, x, x, o, o, x, x],
  [x, o, x, x, x, o, o, x],
  [x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x],
];

export const wheat = [
  [x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x],
  [x, x, x, x, o, o, o, x],
  [x, x, x, o, o, o, x, x],
  [x, x, x, o, o, x, x, x],
  [x, x, o, x, x, x, x, x],
  [x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x],
];

export const balloon = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, x, x, x, x, x, o, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, o, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, o, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, o, o, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const banana = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const batter = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, o, x, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, x, o, x, o, o, o, x, x],
  [x, o, x, x, o, o, o, o, x, o, x, o, x, x, o, x],
  [x, o, o, o, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const battery = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, x, x, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, x, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const bean = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const beastbone = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const beasthide = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, o, o, x, x, o, o, o, o, x, x, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, x, o, o, x, o, o, o, o, x, x],
  [x, x, o, o, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const beastblood = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const beastmeat = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, x, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, x, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, x, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, x, o, x, x, x, x, x, x, x],
  [x, o, o, o, x, x, o, o, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const belt = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, x, x, x, o, o, o, o, o, x, x],
  [x, o, o, o, o, x, x, x, x, x, x, o, o, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, o, x, o, o, o, o, x, x, x, x, x, o, o, x, x],
  [x, o, x, o, x, x, o, x, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, x, x, o, x, o, o, o, o, o, x, o, x],
  [x, x, x, o, o, o, o, x, x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const berry = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const birdhouse = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x, x, o, o, x, x, x, x, x],
  [x, x, x, o, o, x, x, o, o, x, x, o, o, x, x, x],
  [x, o, o, x, x, o, o, o, o, o, o, x, x, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, x, x, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, x, o, o, x, o, o, o, x, x, x],
  [x, x, x, o, o, o, x, o, o, x, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, x, x, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const blanket = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const bug = [
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, o, x, x, x, x, x, x],
  [x, x, o, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, o],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [o, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, x, o, x, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const bugzapper = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, x, o, x],
  [x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, o, o, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, o, x, x],
  [x, o, x, x, x, o, o, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, o, o, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, x, x, x, x, o, x],
  [x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, o, o, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const butterflynet = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, x, o, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, x, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, x, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, x, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, x, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, o, x, o, x],
  [x, x, x, x, x, x, o, x, x, x, o, o, x, o, o, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, o, o, x, x],
  [x, x, x, x, x, o, x, x, x, x, o, o, o, o, x, x],
  [x, x, x, x, o, x, x, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, x, x, x, o, o, o, o, o, o, x, x, x],
  [x, x, o, x, x, x, x, x, o, o, o, o, x, x, x, x],
  [x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const butter = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const cinnamon = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const chopsticks = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, o, x],
  [x, x, x, x, x, o, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, o, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x],
  [x, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const clam = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const clay = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const cloth = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const coconut = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const coffeebeans = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const cotton = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const cupcake = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, x, x, o, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, x, o, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, x, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, x, x, o, o, o, o, o, o, o, x, o, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const diamond = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const crab = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, o, o, o, x, x],
  [x, o, o, o, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, x, o, o, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, o, x, o, o, o, o, o, o, x, o, x, x, x],
  [x, x, x, x, o, o, x, o, o, x, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const dough = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const egg = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const fish = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, o, o, o, o, x],
  [x, x, x, x, o, o, o, o, x, o, o, x, o, x, o, x],
  [x, x, x, o, o, o, o, o, x, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, o, o, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const flour = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const flower = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, x, x, x, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, x, x, x, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, x, x, x, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const fruitsalad = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, x, o, o, x],
  [x, o, x, o, x, o, x, x, x, o, o, x, o, o, o, x],
  [x, o, o, o, o, o, o, x, x, x, x, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, x, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, x, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const glue = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const glass = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, o, o, x, x, x, x, o, o, o, o, x, x, x, x],
  [x, x, x, o, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const hammer = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const fur = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, o, x, x, x, x, x],
  [x, x, o, o, x, x, o, o, x, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, o, x, x, x],
  [x, x, x, x, x, o, x, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const hardcandy = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const grass = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, x, o, x, o, x, x, x, o, x, x, x, x],
  [x, x, x, x, x, o, x, o, x, x, o, o, x, x, o, x],
  [x, x, x, x, x, o, x, o, x, x, o, o, x, x, o, x],
  [x, x, x, x, x, o, o, o, x, o, o, o, x, x, o, x],
  [x, x, x, x, o, x, o, o, x, o, o, x, x, x, o, x],
  [x, x, x, x, o, o, o, o, x, o, o, x, x, o, o, x],
  [x, x, x, o, x, o, o, x, o, o, o, x, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, x, o, o, o, x, x],
  [x, x, o, x, o, o, o, o, o, x, o, o, o, x, x, x],
  [x, o, x, o, o, o, o, x, x, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const herbs = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, o, x, x, x, x, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const icecream = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, o, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, x, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, x, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, o, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const integratedcircuit = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, o, x, o, o, x, x, x],
  [x, x, x, x, x, o, o, x, o, o, o, x, o, o, x, x],
  [x, x, x, x, o, o, o, o, x, o, x, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, x, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const junkparts = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, o, x],
  [x, x, x, x, o, o, x, o, o, x, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, x, x, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, x, x, x, x, o, o, o, x, x, x],
  [x, x, x, o, o, o, x, x, x, x, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, x, x, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, x, o, o, x, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const lace = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, o, o, o, x, x, x, x],
  [x, x, x, o, o, x, o, o, o, o, x, o, o, x, x, x],
  [x, x, o, x, o, o, o, o, o, o, o, o, x, o, x, x],
  [x, o, o, o, x, o, x, o, o, x, o, x, o, o, o, x],
  [x, o, x, o, o, o, x, o, o, x, o, o, o, x, o, x],
  [x, o, o, o, x, x, o, x, x, o, x, x, o, o, o, x],
  [x, x, o, o, o, o, x, x, x, x, o, o, o, o, x, x],
  [x, x, o, o, o, o, x, x, x, x, o, o, o, o, x, x],
  [x, o, o, o, x, x, o, x, x, o, x, x, o, o, o, x],
  [x, o, x, o, o, o, x, o, o, x, o, o, o, x, o, x],
  [x, o, o, o, x, o, x, o, o, x, o, x, o, o, o, x],
  [x, x, o, x, o, o, o, o, o, o, o, o, x, o, x, x],
  [x, x, x, o, o, x, o, o, o, o, x, o, o, x, x, x],
  [x, x, x, x, o, o, o, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const knife = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, x, o, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const magicalpowder = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, x, o, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, o, x, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x],
  [x, x, o, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, o, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [o, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
];

export const lemon = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const milk = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const melon = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const markers = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, o, o, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, o, o, o, x, x],
  [x, x, x, x, o, o, o, x, x, x, o, o, o, x, x, x],
  [x, x, x, o, o, o, x, x, x, o, o, o, x, x, x, x],
  [x, x, o, o, o, x, x, x, o, o, o, x, x, x, x, x],
  [x, o, o, o, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, o, o, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const mug = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, x, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, x, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const nails = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, o, x, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, o, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const octopus = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, x, o, x, o, x, x],
  [x, x, x, x, o, o, o, o, x, o, x, o, o, o, x, x],
  [x, x, x, x, x, o, o, o, x, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, x, o, o, x],
  [x, x, x, x, x, o, o, o, x, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, x, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const paint = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, x, x, o, o, o, o, x, x, x, x],
  [x, x, x, o, x, o, x, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const photoframe = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, o, x, o, o, o, o, o, o, o, o, o, o, x, o, x],
  [x, o, x, o, o, o, o, o, o, o, o, o, o, x, o, x],
  [x, o, x, o, o, o, o, o, o, o, o, o, o, x, o, x],
  [x, o, x, o, o, o, o, o, o, o, o, o, o, x, o, x],
  [x, o, x, o, o, o, o, o, o, o, o, o, o, x, o, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const picnicbasket = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, x, o, o, x, o, o, o, x, x, x, x],
  [x, x, o, o, o, x, o, o, x, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const pie = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, o, x, x, o, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, o, x, x, o, x, x, o, x, x, x],
  [x, x, o, x, x, o, x, x, o, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, o, x, x, o, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const ricebowl = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const ramen = [
  [x, x, o, x, x, o, x, x, o, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, o, x, x, o, x, x, o, x, x, x],
  [x, x, o, x, x, o, x, x, o, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, o, x, x, o, x, x, o, x, x, x],
  [x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, o, o, x, x, x],
  [x, o, x, o, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, x, o, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, x, o, x, o, o, o, o, o, o, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const rope = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, x, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, o, o, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, x, o, o, x, o, o, x, x, x, x],
  [x, x, o, o, x, x, o, x, x, x, x, o, o, x, x, x],
  [x, x, o, x, x, x, o, x, x, x, x, x, o, x, x, x],
  [x, x, o, o, x, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const salt = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const seashell = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const scissors = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, x, x, x, x, o, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, o, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, o, x, o, o, x, x, o, o, x, x, x, x, x, x, x],
  [x, o, x, o, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, o, o, x, x, x, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const shinystone = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const stickers = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const string = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, x, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, x, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, x, o, o, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, o, o, x, x, o, o, o, o, x, o, x, x, x, x, x],
  [x, o, o, o, o, x, o, o, x, x, o, x, x, x, x, x],
  [x, x, o, o, o, o, x, x, x, x, o, x, x, x, x, x],
  [x, x, o, o, o, o, x, x, x, x, o, o, x, o, x, x],
  [x, x, x, o, o, o, o, x, x, x, x, x, o, x, x, x],
  [x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const stew = [
  [x, x, o, x, x, o, x, x, o, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, o, x, x, o, x, x, o, x, x, x],
  [x, x, o, x, x, o, x, x, o, x, x, o, x, x, x, x],
  [x, x, x, o, x, x, o, x, x, o, x, x, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const silk = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const sugarcane = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const sugar = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, x, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const teabag = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const umbrella = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, x, x, o, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, o, o, o, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, o, x, x],
  [x, o, x, x, x, o, x, x, x, x, x, x, x, o, x, x],
  [x, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const tropicaljuice = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, o, x, x, x, x, o, x, x, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const vanilla = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, x, x, o, x, x],
  [x, x, x, x, x, o, o, o, x, x, x, o, o, x, x, x],
  [x, x, o, o, o, o, x, x, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, x, x, o, x, x, x, o, x],
  [x, x, x, x, o, o, o, x, o, x, o, x, o, x, x, x],
  [x, x, o, o, x, x, x, x, x, o, o, o, x, x, x, x],
  [x, o, x, x, x, x, x, o, x, o, o, o, x, x, x, x],
  [x, x, x, x, x, o, o, x, o, x, o, x, o, x, x, x],
  [x, x, x, o, o, x, x, x, x, x, o, x, x, x, x, x],
  [x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const uselesspoo = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const water = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, o, o, o, x, x, x, x, x],
  [x, x, x, x, x, o, o, o, o, o, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];

export const wood = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x],
  [x, x, x, x, x, x, x, x, x, o, o, o, o, o, x, x],
  [x, x, x, x, x, x, x, x, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, x, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, x, x, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, x, o, o, o, o, o, o, o, o, o, o, o, o, x],
  [x, x, o, o, o, o, o, o, o, o, o, o, o, o, x, x],
  [x, o, x, x, o, o, o, o, o, o, o, o, o, x, x, x],
  [x, o, o, o, x, o, o, o, o, o, o, x, x, x, x, x],
  [x, o, o, o, o, x, x, o, o, o, x, x, x, x, x, x],
  [x, x, x, o, o, o, o, x, o, x, x, x, x, x, x, x],
  [x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
];
