/*
  Warnings:

  - The values [REFERRAL_PLAY_MINUTES,FRIEND_PLAY_MINUTES,ADD_FRIEND,ADD_REFERRAL,RAFFLE_PARTICIPATION,BATTLE_PARTICIPATION] on the enum `TaskType` will be removed. If these variants are still used in the database, this will fail.

*/


-- AlterEnum
BEGIN;
CREATE TYPE "TaskType_new" AS ENUM ('PLAY_GAME', 'PLAY_MINUTES', 'VISIT_WEBSITE', 'VISIT_FACEBOOK', 'VISIT_INSTAGRAM', 'VISIT_TIKTOK', 'VISIT_YOUTUBE', 'FOLLOW_TWITTER', 'REPOST_TWITTER', 'BASIC_ACTION', 'WATCH_AD', 'FOLLOW_TWITCH', 'WISHLIST_STEAM_GAME', 'JOIN_DISCORD_GUILD', 'SUBMIT_LEADERBOARD_SCORE', 'SUBSCRIBE_YOUTUBE', 'CAPTCHA', 'FORM', 'POLL', 'SECRET', 'REFERRAL_TASK');
DELETE FROM "Task" WHERE "type" IN ('REFERRAL_PLAY_MINUTES', 'FRIEND_PLAY_MINUTES', 'ADD_FRIEND', 'ADD_REFERRAL', 'RAFFLE_PARTICIPATION', 'BATTLE_PARTICIPATION');
ALTER TABLE "Task" ALTER COLUMN "type" TYPE "TaskType_new" USING ("type"::text::"TaskType_new");
ALTER TYPE "TaskType" RENAME TO "TaskType_old";
ALTER TYPE "TaskType_new" RENAME TO "TaskType";
DROP TYPE "TaskType_old";
COMMIT;
