import { SERVER_SETTINGS } from '@worksheets/data-access/server-settings';

export const urls = {
  relative: {
    home: '/',
    puzzle: `/puzzle`,
    levels: `/levels`,
    gallery: `/gallery`,
    game: `/game`,
    games: `/games`,
    play: `/play`,
    about: `/about`,
    directory: `/directory`,
    terms: `/terms`,
    privacy: `/privacy`,
    contact: `/contact`,
    hire: `/hire`,
    cookies: `/cookies`,
    blog: `/blog`,
    donate: `/donate`,
    faq: `/faq`,
  },
  mailTo: {
    gwenythAdmin: `mailto:miguel@gwenyth.io`,
  },
  social: {
    linkedIn: `https://www.linkedin.com/in/miguel-campos-5b1114172/`,
    twitter: `https://twitter.com/`,
    facebook: `https://www.facebook.com/`,
    github: `https://github.com/GwenythIO/worksheets.dev`,
    personalGithub: `https://github.com/ggonryun`,
    discord: `https://discord.gg/Auatjee2BZ`,
  },
  freeRice: () => 'https://freerice.com/',
  waterOrg: () => 'https://www.water.org/',
  charityWater: () => 'https://www.charitywater.org/',
  fullstory: () => 'https://www.fullstory.com/',
  g2ss: () => 'https://www.g2ss.com/',
  navwar: () => 'https://www.navwar.navy.mil/',
  sdsu: () => 'https://www.sdsu.edu/',
  usd: () => 'https://www.sandiego.edu/',
  worksheets: () => SERVER_SETTINGS.WEBSITES.WORKSHEETS_URL(),
  charityGames: {
    home: () => SERVER_SETTINGS.WEBSITES.CHARITY_GAMES_URL(),
    games: () => SERVER_SETTINGS.WEBSITES.CHARITY_GAMES_URL('/games'),
    contact: () => SERVER_SETTINGS.WEBSITES.CHARITY_GAMES_URL('/contact'),
    newsletter: () => SERVER_SETTINGS.WEBSITES.CHARITY_GAMES_URL('/subscribe'),
  },
  games: {
    puzzleWords: () => SERVER_SETTINGS.WEBSITES.PUZZLE_WORDS_URL(),
    wordPack: () => SERVER_SETTINGS.WEBSITES.WORD_PACK_URL(),
    wordSearch: () => SERVER_SETTINGS.WEBSITES.WORD_SEARCH_URL(),
    emojiWar: () => SERVER_SETTINGS.WEBSITES.EMOJI_WAR_URL(),
    wordSmith: () => SERVER_SETTINGS.WEBSITES.WORD_SMITH_URL(),
    nonograms: () => SERVER_SETTINGS.WEBSITES.NONOGRAMS_URL(),
    solitaire: () => SERVER_SETTINGS.WEBSITES.SOLITAIRE_URL(),
  },
};
