import { Point } from '@worksheets/phaser/types';

/**
 * Generate equidistant points horizontally with edge gaps included in spacing.
 *
 * @param numPoints - The number of points to generate.
 * @param containerWidth - The total width of the container.
 * @param edgeGap - The gap to maintain on both the left and right sides.
 * @param y - The fixed y-coordinate for all points.
 * @returns An array of points with {x, y} coordinates.
 * @remarks Generated by ChatGPT.
 */
export const generateEquidistantPoints = (
  numPoints: number,
  containerWidth: number,
  edgeGap: number,
  y: number
): Point[] => {
  if (numPoints <= 0) {
    throw new Error('Number of points must be greater than zero.');
  }
  if (containerWidth <= 2 * edgeGap) {
    throw new Error('Container width must be greater than twice the edge gap.');
  }

  const usableWidth = containerWidth - 2 * edgeGap;
  const spacing = usableWidth / (numPoints - 1);

  return Array.from({ length: numPoints }, (_, i) => ({
    x: edgeGap + i * spacing,
    y,
  }));
};
