export type Puzzle = {
  words: string[];
  columns: number;
  rows: number;
};

export const puzzles: Puzzle[] = [
  {
    columns: 4,
    rows: 4,
    words: ['ACE', 'AIR', 'AIM', 'ARE', 'ART', 'APE', 'ARM'],
  },
  {
    columns: 4,
    rows: 4,
    words: ['BEE', 'TREE', 'SEE', 'TRY', 'FLY'],
  },
  {
    columns: 5,
    rows: 5,
    words: ['CAT', 'DOG', 'RAT', 'BAT', 'HAT', 'MAT'],
  },
  {
    columns: 5,
    rows: 5,
    words: ['DOOR', 'FLOOR', 'POOR', 'BOAR', 'ROAR'],
  },
  {
    columns: 5,
    rows: 5,
    words: ['EAR', 'TOE', 'EYE', 'LIP', 'ARM', 'LEG'],
  },
  {
    columns: 6,
    rows: 6,
    words: ['FAR', 'FAME', 'FREE', 'FIRE'],
  },
  {
    columns: 6,
    rows: 6,
    words: ['GUN', 'GUM', 'GEM', 'GAP', 'GAL', 'GOD', 'GAS', 'GAG'],
  },
  {
    columns: 9,
    rows: 9,
    words: [
      'APPLE',
      'BANANA',
      'CHERRY',
      'GRAPE',
      'ORANGE',
      'PEAR',
      'MELON',
      'AVOCADO',
      'KIWI',
    ],
  },
  {
    columns: 10,
    rows: 10,
    words: [
      'TROUT',
      'SALMON',
      'BASS',
      'PERCH',
      'COD',
      'TUNA',
      'PIKE',
      'CARP',
      'EEL',
      'GOLDFISH',
      'CATFISH',
      'SWORDFISH',
    ],
  },
  {
    columns: 11,
    rows: 11,
    words: [
      'ENGINE',
      'BRAKE',
      'WHEEL',
      'STEERING',
      'BATTERY',
      'LIGHTS',
      'RADIO',
      'WIPERS',
      'MIRROR',
      'GEARBOX',
    ],
  },
  {
    columns: 12,
    rows: 12,
    words: [
      'PIE',
      'CAKE',
      'CANDY',
      'COOKIE',
      'BROWNIE',
      'PUDDING',
      'CUPCAKE',
      'DONUT',
      'CUSTARD',
      'FUDGE',
      'BISCUIT',
    ],
  },
  {
    columns: 13,
    rows: 13,
    words: [
      'BANJO',
      'BASS',
      'CELLO',
      'CLARINET',
      'DRUM',
      'FLUTE',
      'GUITAR',
      'HARP',
      'HORN',
      'PIANO',
      'SAXOPHONE',
    ],
  },
  {
    columns: 14,
    rows: 14,
    words: [
      'BEETLE',
      'BUTTERFLY',
      'CATERPILLAR',
      'CENTIPEDE',
      'DRAGONFLY',
      'EARWIG',
      'FIREANT',
      'FLEA',
      'FLY',
      'GRASSHOPPER',
      'LADYBUG',
      'LOCUST',
      'MANTIS',
      'MOSQUITO',
      'MOTH',
      'SCORPION',
      'SPIDER',
      'TARANTULA',
      'WASP',
      'WORM',
    ],
  },
];
