const DISCORD_ADMIN_WEBHOOK_URL =
  process.env['DISCORD_ADMIN_WEBHOOK_URL'] ?? '';
const DISCORD_PUBLIC_WEBHOOK_URL =
  process.env['DISCORD_PUBLIC_WEBHOOK_URL'] ?? '';

if (!DISCORD_ADMIN_WEBHOOK_URL) {
  throw new Error('DISCORD_ADMIN_WEBHOOK_URL is not defined');
}
if (!DISCORD_PUBLIC_WEBHOOK_URL) {
  throw new Error('DISCORD_PUBLIC_WEBHOOK_URL is not defined');
}

export { DISCORD_PUBLIC_WEBHOOK_URL, DISCORD_ADMIN_WEBHOOK_URL };
