import { RecommendationsSchema } from '@worksheets/util/types';

// TODO: this should be fetched from a database.
export const recommendations: RecommendationsSchema = {
  featured: [
    'baku-gamu',
    'blasteroids',
    'stick-jump',
    'solitaire',
    'air-hockey-neon',
    'quickbeat',
    'solitaire-2048',
    'puzzle-words',
  ],
  popular: [
    'baku-gamu',
    'invention-timeline-game',
    'fragile-floor',
    'quickbeat',
    'solitaire-2048',
    'stick-jump',
    'air-hockey-neon',
    'kuttuk',
    'solitaire',
    '1d-chess',
    'freedom-run',
  ],
  new: [
    'blasteroids',
    'skwatta',
    '1d-chess',
    'feaare',
    'kuttuk',
    'conquer-the-world',
    'fragile-floor',
    'baku-gamu',
    'invention-timeline-game',
    'quickbeat',
    'dino-rush',
    'stick-jump',
    'freedom-run',
    'plane-fly',
    'solitaire-2048',
    'air-hockey-neon',
  ],
  categories: [
    'ad-free',
    'card',
    'board',
    'puzzle',
    'brain',
    'action',
    'word',
    'popular',
    'mobile',
  ],
};
