import { RecommendationsSchema } from '@worksheets/util/types';

export const recommendations: RecommendationsSchema = {
  popular: [
    'fragile-floor',
    'baku-gamu',
    'freedom-run',
    'solitaire-2048',
    'stick-jump',
    'air-hockey-neon',
    'solitaire',
  ],
  new: [
    'fragile-floor',
    'baku-gamu',
    'word-search',
    'word-pack',
    'puzzle-words',
    'nonograms',
    'word-smith',
    'stick-jump',
    'freedom-run',
    'plane-fly',
    'solitaire-2048',
    'air-hockey-neon',
    'solitaire',
    'emoji-war',
  ],
  categories: [
    'ad-free',
    'card',
    'board',
    'puzzle',
    'brain',
    'action',
    'word',
    'popular',
    'mobile',
  ],
};
