import { TRPCError } from '@trpc/server';

export * from './lib/failures';

export const TRPC_ERROR_CODE_HTTP_STATUS: Record<TRPCError['code'], number> = {
  PARSE_ERROR: 400,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  TIMEOUT: 408,
  CONFLICT: 409,
  CLIENT_CLOSED_REQUEST: 499,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  METHOD_NOT_SUPPORTED: 405,
  TOO_MANY_REQUESTS: 429,
  UNPROCESSABLE_CONTENT: 422,
};

export const HTTP_STATUS_CODE_TRPC_ERROR: Record<number, TRPCError['code']> = {
  400: 'BAD_REQUEST',
  404: 'NOT_FOUND',
  500: 'INTERNAL_SERVER_ERROR',
  401: 'UNAUTHORIZED',
  403: 'FORBIDDEN',
  408: 'TIMEOUT',
  409: 'CONFLICT',
  499: 'CLIENT_CLOSED_REQUEST',
  412: 'PRECONDITION_FAILED',
  413: 'PAYLOAD_TOO_LARGE',
  405: 'METHOD_NOT_SUPPORTED',
  429: 'TOO_MANY_REQUESTS',
  422: 'UNPROCESSABLE_CONTENT',
};
